authentication:
  provider: jwt
  public_key_path: /secrets/jwt_public.pem
  issuer: "pr-generator-auth"
  audience: "pr-generator-mcp"

authorization:
  default_policy: deny
  
  tool_permissions:
    analyze_repository:
      roles: ["developer", "admin"]
      scopes: ["repo:read"]
    
    suggest_pr_boundaries:
      roles: ["developer", "admin"]
      scopes: ["repo:read", "ai:use"]
    
    create_pull_request:
      roles: ["developer", "admin"]
      scopes: ["repo:write", "pr:create"]
  
  rate_limits:
    - role: developer
      requests_per_hour: 100
    - role: admin
      requests_per_hour: 1000

audit:
  enabled: true
  log_level: info
  sensitive_fields:
    - auth_token
    - api_key
